# Generated by Django 3.0.5 on 2020-04-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smithworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontier',
            name='tier_level',
            field=models.IntegerField(),
        ),
    ]
