# Generated by Django 3.0.5 on 2020-04-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smithworks', '0002_auto_20200412_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='PA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
